spring:
  profiles:
    active: dev
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          username: mes2
          password: mes
          url: jdbc:mysql://10.0.0.39:3306/mes?useUnicode=true&characterEncoding=utf-8
          driver-class-name: com.mysql.cj.jdbc.Driver
        second:
          username:
          password:
          url: jdbc:sqlite:D:/Codes/Java/attachInfo.db
          driver-class-name: org.sqlite.JDBC

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    # 开启mybatis的下划线-驼峰命名映射
    map-underscore-to-camel-case: true

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8089

logging:
  level:
    cc.ilooli: debug
---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8090

logging:
  file:
    name: log.txt
